# Generated by Django 5.1.7 on 2025-03-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monTiGMagasin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='price',
        ),
        migrations.AddField(
            model_name='infoproduct',
            name='prixvente',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='prixcht',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='prixvente',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('achat', 'Achat'), ('vente', 'Vente'), ('peremption', 'Péremption')], default='achat', max_length=20),
        ),
    ]
