# Generated by Django 5.1.7 on 2025-03-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monTiGMagasin', '0003_rename_prixcht_transaction_priceachat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='priceachat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='prixvente',
            field=models.FloatField(),
        ),
    ]
